version: '3.4'

services:
  rosmery.security.ui:
    image: rosmery.security.ui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"